FROM openjdk:17-jdk-slim

ARG WORK_DIR=/opt/app/backend

WORKDIR ${WORK_DIR}
COPY . ${WORK_DIR}

ARG JAR_FILE=/target/*.jar

COPY ${JAR_FILE} app.jar

ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=prod", "app.jar"]